# training parameters
training:
    pixImgPath: /home/nansong/Dropbox/collaborative_ws/net_ws/src/randomforest/data/images/final
    trueImgPath: /home/nansong/Dropbox/collaborative_ws/net_ws/src/randomforest/data/images/origin
    img_size: [160, 120]
    NUM_TRAIN: 250
    batch_size: 4
    NOISE_DIM: 1200
    num_epochs: 200
    show_every: 300
